### PR TITLE
README.md: update git pull to point to github.com

### PR DESCRIPTION
**Pull request by wdconinc**

### CODE REVIEW

**Comment by wdconinc** [comment]
@veprbl Do you have any idea why the macos-lcg tests fail? I don't have a mac to test, but maybe you can test this? Don't feel obliged, though, since this requires 1) macOS 10.15, 2) installing cvmfs, 3) loading the LCG view. It is the closest we are going to get to being able to run CI against a macOS target.

**Comment by wdconinc** [comment]
Actually, @sly2j you have a mac too. Do you know what is wrong with the macos-lcg check here? See previous comment.

**Comment by veprbl** [comment]
Looking at the log, I think I saw this problem before. For me it was due to the XML parser the dd4hep is built against: xerces-c or TinyXML. We need to use correct character type on our end (perhaps, there is a typedef for it in dd4hep).

**Comment by veprbl** [comment]
Here is what I see when compiling against DD4hep that is built with `-DDD4HEP_USE_XERCESC=ON`:
```
/tmp/nix-build-ip6.drv-0/source/src/B0Preshower_geo.cpp:67:24: error: cannot initialize a parameter of type 'const dd4hep::xml::XmlChar *' (aka 'const char16_t *') with an lvalue of type 'const char [6]'
    if (x_mod.hasChild("frame")) {
                       ^~~~~~~
/nix/store/21dqkpgfy5dsakzpnanxfg55zbc8n2pf-DD4hep-01-20-02/include/XML/XMLElements.h:912:36: note: passing argument to parameter 'tag_value' here
      bool hasChild(const XmlChar* tag_value) const {
                                   ^
/tmp/nix-build-ip6.drv-0/source/src/B0Tracker_geo.cpp:77:24: error: cannot initialize a parameter of type 'const dd4hep::xml::XmlChar *' (aka 'const char16_t *') with an lvalue of type 'const char [6]'
    if (x_mod.hasChild("frame")) {
                       ^~~~~~~
/nix/store/21dqkpgfy5dsakzpnanxfg55zbc8n2pf-DD4hep-01-20-02/include/XML/XMLElements.h:912:36: note: passing argument to parameter 'tag_value' here
      bool hasChild(const XmlChar* tag_value) const {
                                   ^
1 error generated.
```

**Comment by wdconinc** [comment]
>
> Yeah, but I fixed that one yesterday so this run shouldn't have
encountered that particular issue. See
https://eicweb.phy.anl.gov/EIC/detectors/ecce/-/commit/896689e04ab2b5038ab62f598d72c398537f8113
896689e04ab2b5038ab62f598d72c398537f8113

This is also now showing up as a linker error, not a compilation error, so
that's confusing me.

**Comment by veprbl** [comment]
Yes. You are right. I am trying to look for inconsistent preprocessor definitions.

Looking at veprbl/ecce#1, it seems like the DD4hep is of an older version:
```
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(26):  set(DD4hep_VERSION 1.15 )
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(27):  set(DD4hep_SOVERSION 1.15 )
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(28):  set(DD4HEP_USE_GEANT4 ON )
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(29):  set(DD4HEP_USE_CLHEP TRUE )
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(30):  set(DD4HEP_USE_LCIO ON )
/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-mac1015-clang120-opt/cmake/DD4hepConfig.cmake(31):  set(DD4HEP_USE_XERCESC ON )
```

**Comment by veprbl** [comment]
> Yeah, but I fixed that one yesterday so this run shouldn't have
> encountered that particular issue. See https://eicweb.phy.anl.gov/EIC/detectors/ecce/-/commit/896689e04ab2b5038ab62f598d72c398537f8113 [896689e](https://github.com/eic/ecce/commit/896689e04ab2b5038ab62f598d72c398537f8113) This is also now showing up as a linker error, not a compilation error, so that's confusing me.

Great! With your fix, I can reproduce the issue locally:
```
Undefined symbols for architecture x86_64:
  "char const* dd4hep::xml::Handle_t::attr<char const*>(char16_t const*) const", referenced from:
      buildFibers(dd4hep::Detector&, dd4hep::SensitiveDetector&, dd4hep::Volume&, dd4hep::xml::Component, std::__1::tuple<double, double, double, double> const&) in BarrelCalorimeterInterlayers_geo.cpp.o
      (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::det_element_ecce_CompositeTracker, dd4hep::NamedObject* (dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*) in CompositeTracker_geo.cpp.o
      build_mirrors(dd4hep::Detector&, dd4hep::DetElement&, dd4hep::Volume&, dd4hep::xml::Component, ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>, ROOT::Math::DefaultCoordinateSystemTag> const&) in GaseousRICH_geo.cpp.o
      (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::det_element_ecce_GaseousRICH, dd4hep::NamedObject* (dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*) in GaseousRICH_geo.cpp.o
      create_detector(dd4hep::Detector&, dd4hep::xml::Handle_t, dd4hep::SensitiveDetector) in HomogeneousCalorimeter_geo.cpp.o
      createDetector(dd4hep::Detector&, dd4hep::xml::Handle_t, dd4hep::SensitiveDetector) in MRich_geo.cpp.o
      build_shashlik(dd4hep::Detector&, dd4hep::xml::Collection_t&, dd4hep::SensitiveDetector&) in ShashlikCalorimeter_geo.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by wdconinc** [comment]
Try to use LCG 101. The LCG 99 doesn't have acts anyway. Unfortunately the most recent LCG 102 only exists for macos-11 which we cannot use on GitHub due to the missing permissions in the GitHub images to use the cvmfs modules.

**Comment by wdconinc** [comment]
I've already removed LCG 99 for that reason but it's still making its way through the CI pipelines on eicweb.

**Pull request merged**
