### PR TITLE
treewide: use explicit getAttrOrDefault<std::string>

### PR DESCRIPTION
**Pull request by veprbl**
This is needed to support DD4hep built with `-DDD4HEP_USE_XERCESC=ON`.

### CODE REVIEW

**Comment by wdconinc** [comment]
Still not able to accept PRs here... Can you file on eicweb? I'm hoping to switch the roles of the mirrors soon, maybe by Monday.

**Comment by wdconinc** [comment]
And, yeah, eicweb has some disk space issues right now, so pipelines will probably fail.

**Review by wdconinc — APPROVED** [review]

**Comment by wdconinc** [comment]
Do we need to add sqlite3 [here](https://github.com/AIDASoft/run-lcg-view/blob/master/run-macOS.sh#L31)?

**Comment by wdconinc** [comment]
I've asked github support to detach the fork https://github.com/eic/run-cvmfs-osg-eic-shell from the upstream. Then we can have a new fork that I'm not going to repurpose. That will help us in figuring out if run-lcg-view needs any changes, and submitting a PR to upstream.

**Comment by veprbl** [comment]
> Do we need to add sqlite3 [here](https://github.com/AIDASoft/run-lcg-view/blob/master/run-macOS.sh#L31)?

I suppose that won't help. I can see `__sqlite3_db_clone` symbol exported from `/usr/lib/libsqlite3.dylib`, but not from a build of sqlite 3.38.5. So, I suppose, the LCG environment must be using `DYLD_LIBRARY_PATH` and that breaks the normal library loading.

**Comment by wdconinc** [comment]
In addition, now the ip6 macos jobs are now hanging until timeout... No idea why.

**Comment by veprbl** [comment]
Link?

**Comment by wdconinc** [comment]
https://github.com/eic/ip6/actions/runs/2644602915

**Pull request merged**
